version: '3'

services:
  back:
    image: valentiiiine/lab_docker:latest
    ports:
      - "5000:5000"
    environment:
      CURRENT_ENVIRONMENT: dev
    #volumes:
    #  - back_data:/app/data

  front:
    image: valentiiiine/flask-front:latest
    ports:
      - "8080:80"
    environment:
      WS_BACK_URL: http://back:5000
    depends_on:
      - back

#volumes:
#  back_data: